config/routes.rb
Instalist::Application.routes.draw do
  devise_for :users

  resources :lists

  get "home/index"

  root :to => 'home#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list  
end

app/models/list.rb
class List < ActiveRecord::Base
  
  validates_presence_of :name
  
  has_many :items, :dependent => :destroy 
  accepts_nested_attributes_for :items, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_filter :authenticate_user!
  
  def index
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  
  before_filter :authenticate_user!
  
  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new
    3.times { @list.items.build }
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instalist</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	
	<div id="user_nav">  
	  <% if user_signed_in? %>  
	    Signed in as <%= current_user.email %>. Not you?  
	    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
	  <% else %>  
	    <%= link_to "Sign up", new_user_registration_path %> or  
	    <%= link_to "Sign in", new_user_session_path %>  
	  <% end %>  
	</div>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
	<fieldset>
		
  	<div class="field">
    	<%= f.label :name %><br />
    	<%= f.text_field :name %>
  	</div>
		
		<ul>
			<%= f.fields_for :items do |item| %>
			  <li>
				  <%= item.check_box :done %>
			    <%= item.label :content, "Item" %><br />  
			    <%= item.text_field :content %>
					<%= item.check_box :_destroy %>
					<%= item.label :_destroy, "Remove item" %>
			  </li>  
			<% end %>
		</ul>
	
	</fieldset>
		
  <div class="actions">
    <%= f.submit %>
  </div>
	
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Listing lists</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lists.each do |list| %>
  <tr>
    <td><%= list.name %></td>
    <td><%= link_to 'Show', list %></td>
    <td><%= link_to 'Edit', edit_list_path(list) %></td>
    <td><%= link_to 'Destroy', list, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @list.name %>
</p>

<% if @list.items %>
	<ul>
		<% @list.items.each do |item| %>
			<li>
		  	<%= item.content %>
			</li>
		<% end %>
	</ul>
<% end %>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>